User.create!(username: "liam.sunderland.93", password_digest: "password")
User.create!(username: "just-steve", password_digest: "password")
User.create!(username: "millls", password_digest: "password")
User.create!(username: "Darkvoid360", password_digest: "password")
User.create!(username: "Stubrew", password_digest: "password")
User.create!(username: "Sofia", password_digest: "password")
User.create!(username: "Sanderman", password_digest: "password")
User.create!(username: "KianKian", password_digest: "password")
User.create!(username: "dandan", password_digest: "password")
User.create!(username: "mickeyg", password_digest: "password")
User.create!(username: "gloveboxed", password_digest: "password")
User.create!(username: "jellz", password_digest: "password")

# user2 = User.create!(username: "liam.sunderland.93")
# user3 = User.create!(username: "just-steve")
# user4 = User.create!(username: "millls")
# user5 = User.create!(username: "user5")

camden = Location.create!(name: "Camden")
greenwich = Location.create!(name: "Greenwich")
hackney = Location.create!(name: "Hackney")
hammersmith = Location.create!(name: "Hammersmith")
islington = Location.create!(name: "Islington")
kensington = Location.create!(name: "Kensington")
lambeth = Location.create!(name: "Lambeth")
lewisham = Location.create!(name: "Lewisham")
southwark = Location.create!(name: "Southwark")
tower_hamlets = Location.create!(name: "Tower Hamlets")
wandsworth = Location.create!(name: "Wandsworth")
westminster = Location.create!(name: "Westminster")

category1 = Category.create!(name: "Entertainment", img_url: "https://images.unsplash.com/photo-1536331014686-7c8210a64010?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80")
category2 = Category.create!(name: "Politics", img_url: "https://images.unsplash.com/photo-1466780446965-2072a3de8a43?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1649&q=80")
category3 = Category.create!(name: "Food & Drink", img_url: "https://images.unsplash.com/photo-1534790566855-4cb788d389ec?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80")
category4 = Category.create!(name: "Sport", img_url: "https://images.unsplash.com/photo-1519766304817-4f37bda74a26?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80")
category5 = Category.create!(name: "Business", img_url: "https://images.unsplash.com/photo-1444653614773-995cb1ef9efa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1655&q=80")
category6 = Category.create!(name: "Charity & Fundraisers", img_url: "https://images.unsplash.com/photo-1535017516924-a5a70754bbc0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1665&q=80")
category7 = Category.create!(name: "Council & Community", img_url: "https://images.unsplash.com/photo-1500021804447-2ca2eaaaabeb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80")
category8 = Category.create!(name: "Agriculture", img_url: "https://images.unsplash.com/photo-1471006549858-a467e342c749?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80")

Event.create!(name: "Charity Comedy Show", description: "12 standups take to the stage throughout the day, serving jokes upon jokes with the aim of raising money for MS.", start_time: DateTime.now, end_time: DateTime.tomorrow, location_id: 1, category_id: 6)

# event1 = Event.create!(name: "Festival", description: "Local Rock Festival", location_id: 1)
# ue = UserEvent.create!(user_id: 1, event_id: 1)
